addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.10.4")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"       % "1.9.3")
addSbtPlugin("com.dwijnand"   % "sbt-dynver"          % "4.1.1")
addSbtPlugin("com.eed3si9n"   % "sbt-assembly"        % "0.14.6")
addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.3")
